language: python
python:
- '3.11'
dist: focal
services:
- sqlite3
before_install:
- sudo apt-get update
- sudo apt-get install sqlite3 libsqlite3-dev
- sqlite3 --version
- pip install awscli
install:
- pip install -r requirements.txt
script:
- python3 manage.py migrate
- python3 manage.py test polls
before_deploy:
- aws s3 ls s3://elasticbeanstalk-us-east-1-522814719927 || echo "Bucket not accessible"
deploy:
  provider: elasticbeanstalk
  access_key_id: "p911xLIcSP4LhZvnDeWMFCemZsERUYvxIvLZGnTq/N3j4XE7u4PnVUkUG0ZHx7NLBdYNIOmhRqWCtxK029W/zAowyOyp+bNCYZoYmeEFQ+quxbpgXB88Mfoh67mwSxOkb95AuQNSq/LVf9N3qU91GAr48bzz//rI8rvS/gqJyADKp9QtC+LozfB1rnNqePvcqqtfJIaxj5uCf7g3PvSwdS6PgQQPXBhCA+rug3izI8IpjCV84vGxbjQ8PUkMUFBZcyaUscOLZyIVbONBh3iw1YpyCt9fJYuMg8EaadT6wuxHGzLL6z/eIwsqrwbW1O7GJqSynShGJtXNPVu8VwRFNpOHGZD2c7U7kGBLM07DWLEtel7V5lbk2AUvCSqcMS9+8udcnNPY0uSUNE5KWTpRg0sxW/4kKBgPITS8UJH0V3CTmRVhi00TAWY3vvIUp8jJQVUT8ycuk7itYsk3ovU3m2OaqFQW8gKfWeo5teYsCei5m0WfMbfQe8udFAOmgmXYeI/r0dyUbtLKap2AcrfAliq3suY/A6pnx/CDsfPWe4RxId78tSDrsbeHefHhXQIxFojkmYYHLdwsKcnJXyUtQ3R0PoUZGp7mG6z/tH0F3b8mBuk0XQ6nfuPzNq0LlUC25Zd+Qj4BIV4Q1r3/vaqhWwTytvwCAOEwRvm4MCiOK74="
  secret_access_key: "3oO2rWI9AA3LpcbnnW22tUy5joRzBzcxWRcVHEfQPXBU62kNRClLFh3dVX06RagCVLuH/woL8ZCj91NVaFgmb6174hGzJCEvgIgTLO+tmutKErfV0NBhelA1d6q+xezSJwHmNTHKBFDuqPn2kfJr6MPayzohyDuMmMUhE9pT4E+WAehqyoIqZn+otHIK0sKdHJ1Be21ivemDHDW2RlcmoHU++aY8X3LzS1j6qGL8bB6g9Pi5ZLgGXrrVoKUiWDNR2nAYwZMytU0TUnpWfynZ4zOgCx5IGbQsK52ai1ZdB9n9dq12fEsGa6PDf1Fi3K2WFXSPZoyr8ITZ4ogJBylZxpL3ppoBgBEND9pm2sMrjOdzJlQbFNrNUZVZwovEYiUu8zrXJdrOyFGJ0Se/Ry7Vn6kcGBsFgU5cwUnDNQl0q7NqxA7+KofSFRI+GEzZJHJoASWsCkR8Up530oTLcKl2nVxhZ8DADEw/YfPwkGPSOAn43u+JJkYd+4pYEa9M70fd2cLMs7bD7ld6PQsBfgL0wmMQWgpb4k58FoQG3p413OIQnh8lNWhwoFqSTQDD40+7wSFJb0KJstclhjBW1R8t5gxq3MQuHqXRwq/O8yiBxHGeX1SHjkSHPntGg+W1GMjely4dLn0+3c6K1SNtAbqt5Xo4RNkkBLgWWvJxLesUFeY="
  region: us-east-1
  app: polls
  env: Polls-env
  bucket_name: elasticbeanstalk-us-east-1-522814719927
  on:
    branch: main