language: python
python:
- '3.11'
dist: focal
services:
- sqlite3
before_install:
- sudo apt-get update
- sudo apt-get install sqlite3 libsqlite3-dev
- sqlite3 --version
- pip install awscli
install:
- pip install -r requirements.txt
script:
- python3 manage.py migrate
- python3 manage.py test polls
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: us-east-1
  app: polls
  env: Polls-env
  bucket_name: elasticbeanstalk-us-east-1-522814719927
  on:
    branch: main
    