language: python
python:
- '3.11'
dist: focal
services:
- sqlite3
before_install:
- sudo apt-get update
- sudo apt-get install sqlite3 libsqlite3-dev
- sqlite3 --version
- pip install awscli
install:
- pip install -r requirements.txt
script:
- python3 manage.py migrate
- python3 manage.py test polls
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: dRF/WEupJMGM9QuC9/8ncRKa3tZkMSbYvyEfhJrTYmdpEhNZtWm9a1mbD7doYuBQb62GRAh0NaHHO3DpvG9c498qZm8oOeY+ABd6ODevujH4YiEkXtu69jpSbmanfBDucXicj5JigfY0P+tNFByHdVKkrkIc9+4r+0O4bzVUZ+V4HZBbUVxHS67dzn4hochjrZIFIFGAabq7buZcXjKa1/KbvCg/VWSaELTaiUyh8eE/65oqowHzbAZMZGQVIVdnA3uff20Rn2sv9bhSZwb/HXfvyGtYig6XTitbkw8GNMUFWlB87Mp569dwDNyXvx1Yjt41AX8e+HG5C1Dc1I6wlVRElWeGROMzYDKK8MtqsJgp61TfaZG5vfEYkkHleFyfDjYvnAHleCl3ksXqh4vtn8sO6AxkcO/e26K4JzSAZd+eRoI6OhrUJdTrezeZcUu37p/fDFgHT31MiPTAp56UpIMCDIfdSWvsM4tV3Is4xU+RHRNgz1TELxJo0aSG6T72YdySw8QZTsvvYwp3ReNNah206wh9RWn3u76uiJOpOgKQh3ly4CgiyAfronKNCi3T+wvOhxujCKRAqSirkiSTFzcIdVmKBBa+g4WKvZi69546a8+l4LcBNpFhShLEICfayosK4erJgclv1q01n/lsRakRuL2ALuw+mrRCa+nGAsM=
  secret_access_key:
    secure: QoEKNoOKGt5VcfNfKOQz8a0N2R4fRT9UFrE4st49Ps5KLqo76Z8iHoBYOf13KhTmNllvYc6jgWvp0u2HUhnWKjdylSlb36q4GqIEM8RMJu+fa9ukXOC/eJDIBny5n7V5gm+kkA3ytZF6WJYBHQvbw56OCX5zlpCP+BHjbHjHAHUPjBWHtUv/xstIfXWizMk98zaEAaLMp4HKD3qwTe9lyb11gcARq99Qqz4oX9HfPZMyg8O68hunqlkendnaNyccRFrWARGV6ueF7s8TmVL1Lv8eas1i8dw2IeTpuFlTpf1oXM2mDx9ACj8koUZdZZ9EpYdbab6TDTcCYphhqpEooVhxxV7u2MYpcUBz7nwS2QH91UCVPSmsi6a3EkZMVDhhOixXGsJDgn6nbDQQxc2NNjPlh4wW6A2PMqQCGQxFgLt4FVvYMa9gVDesQAJM2VXwyLjPH65h6J3sFG02pY+EhAYhIHXPaXXz8bikweehONFPWZUhPxsjT36XI+5Khh/HkEbd4gMK4IB+rH9cnL9TSOTTDjTIXpE00Jv1dIGm2Hair60aXjgqRFtoYL0CTjjVElssLm62W/ZtY/hyeMOdCVOd6XIDv32vgXHWwNHxiWFTMTMQLIz2Qg0Tid9M2vlK69lCbc/fuL288/DcW6CgITU6Gkro5SGUadtdAIZc+RM=
  region: us-east-1
  app: polls
  env: Polls-env
  bucket_name: elasticbeanstalk-us-east-1-522814719927
  on:
    branch: main
env:
  global:
  - secure: 1a+RYSCXig16By7cKxcO4J7Ym2NWxHYV8wbPRNaQGY6V4SK42/fI5PuZ/8Wm/GsGaOhtRi9STpeYBOqKwDyehg/jS1t7oZDlMUYdwlFNxAH3CBMERCfFz2e3TEQOgqCya8Xca/mJsEnbrACq+VU+o1hIVcySvE+EfybiV5HAcxyOhMgyQ3JPHH/KhPzC619ZUTR/yLqNkQ+nt/R+83VzoiFHmez18CX4ykdnqoh+/rej7130vJ6HWfwTyjWu4vT/OsNr5ZsjMkXhuLuMpuclSOSOM31ez3h7TSfFQj/PcJb64NRCF95VdoYr6CEzQUhNe0Z0Zj0PE2D7lQ8G1igiEOxQqOFN6NcYM6FR5smyCNT7CelJJZf5vaTLfekEvhO1UzNdrzVwi0E9zNuBVtSxJBOcWHq1Q8SYLTzSY0GJCrMli3nSf2X1k6OXGsYT2sYLP4vDsC4pzNTPFS0cP4a35GcfMLlEkUplJlVvhcdeJypqe5D9MCTxG4sNpR/2n72kcxFajOstQjLbn2N0N2g7zVOhb1DQD5s+JvEgBcPpl47AmOzD8ZWG6boS3b4VOFc+m2adBydLNDX6eQtvuWZ2VCRBL9iMhi1Ei1JsTkE3eXxUppyC8Kutz3wfcc38XwJzuiNIsCqbvQOurWiAuXpVqrCh2n1HTItXyN2+6I/PKaA=
  - secure: zzh3RiEKl+L5pxjqllvJF/qoLj2eKWUxScg2FP0HBrZ3bZw42uxdBtc7JEr6RyhBKKhEf2CJZnR+ik1jn/Fj8C4Eo/0TEtjIOO8wDOu1vx+IMFyEe8F2OXNg8IuG3YzBr7YynnI+FaSt8wn3sfDEU4kF5Vw+sB47CkeeJ9O00jYB7cRB8DliFM7fc8Od8zP4k3FYDOtZYWjHgMZ0NlbQ4zVwA6s8ahiCCp/hJCv4L4MmiO28DUK1Gi2+rf2FXOLDaAi00xqmPhhX6gfo6xe8HIkndCsT5BqUgs23BlzvW6LmKAczLLson4WN3uy6uvXdxL17gkQj3+WXttY9ywurJ9+9K3M5zkX161oRjyVMciCJzW5RekJSMCmJ4r26CN4LM2PArXprWx/Eg+alvcsOwwSTg9nlx15EumiynEduY+nz3AhwXo3DxjybR7iZsigTPKlwBWdFShXCy1y+vHUf6ogHYA9rN0QumVV2dtwCd+nI2BBatLWcwNKPnxaAJIs+bbkIzEghmRrOpxloZcnw4cOBAFEtsLar0BmIu8IWhn10Yc9jkiOutp0RmwKJ3HTavNYiRDn5mgPmdJi8BSjBBX5+vfo5O7UbjtUenTqHdjqwDLzwtDtN4YnqoHTig7IcT+qhMUO1v6QvlTE7+5eTtsvdpmG3PzXbQKA0FmuhurA=
