language: python
python:
  - '3.11'
dist: focal
install:
  - pip install -r requirements.txt
before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput
script:
  - black --check ./mysite ./polls
  - flake8 ./mysite ./polls
  - coverage run --source='polls,mysite' manage.py test
after_script:
  - coveralls
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: us-east-1
  app: polls
  env: Polls-env
  bucket_name: elasticbeanstalk-us-east-1-522814719927
  on:
    branch: main